package juegoahorcado;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Miquel A. Fuster
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    // Contiene las imagenes a mostrar del ahorcado
    ImageIcon[] imgIntentos = new ImageIcon[7];
    
    // Lista con todas las frases que se van a usar durante la partida
    String[] titulosPelicula = { "alguien volo sobre el nido del cuco",
                                 "la caza del octubre rojo",
                                 "los diez mandamientos",
                                 "el bueno, el feo y el malo",
                                 "la vida de bryan",
                                 "los caballeros de la mesa cuadrada",
                                 "buscando a nemo",
                                 "el señor de los anillos",
                                 "pulp fiction",
                                 "la lista de schindler",
                                 "el nombre de la rosa",
                                 "la guerra de las galaxias",
                                 "el padrino",
                                 "lawrence de arabia",
                                 "con faldas y a lo loco",
                                 "centauros del desierto",
                                 "cantando bajo la lluvia",
                                 "la novia de frankenstein",
                                 "metropolis" };
    
    // Lista de frases aleatorias que faltan por adivinar
    String[] listaEnJuego;
    
    // Índice que indica la frase de listaEnJuego con la que se está jugando
    int indiceActual;
    
    // Índice de la última película de la listaEnJuego válida
    int indiceFinal;
                                 
    // Contiene la frase que se va a buscar
    String textoOculto;
    
    // Contiene las letras que se han introducido en el juego actual
    String letrasIntroducidas;
    
    // Contiene la cadena oculta que va a ver el usuario.
    StringBuilder cadenaResultado;
    
    // Número de errores del juego actual
    int fallos;
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        // Carga las imagenes a usar.
        for(int i = 0; i < 7; ++i) {
            imgIntentos[i] = new ImageIcon("imagenes/imagen" + (i+1) + ".gif");
        }
        
        initComponents();
        
        // Deja el juego listo para iniciarse
        reiniciarJuego(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        panelIzquierdo = new javax.swing.JPanel();
        panelDibujo = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        panelDerecho = new javax.swing.JPanel();
        lblInformacion = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        lblFraseOculta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del ahorcado");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        panelBase.setLayout(new java.awt.GridLayout(1, 2));

        panelIzquierdo.setBackground(new java.awt.Color(255, 255, 255));
        panelIzquierdo.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelIzquierdo.setLayout(new java.awt.BorderLayout());

        panelDibujo.setBackground(new java.awt.Color(255, 255, 255));
        panelDibujo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDibujo.setLayout(new java.awt.BorderLayout());

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(imgIntentos[0]);
        lblImagen.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelDibujo.add(lblImagen, java.awt.BorderLayout.CENTER);

        panelIzquierdo.add(panelDibujo, java.awt.BorderLayout.CENTER);

        panelBase.add(panelIzquierdo);

        panelDerecho.setBackground(new java.awt.Color(255, 255, 255));
        panelDerecho.setLayout(new java.awt.BorderLayout());

        lblInformacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblInformacion.setForeground(new java.awt.Color(0, 0, 255));
        lblInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformacion.setText("Letras:");
        panelDerecho.add(lblInformacion, java.awt.BorderLayout.CENTER);

        panelBase.add(panelDerecho);

        getContentPane().add(panelBase, java.awt.BorderLayout.CENTER);

        panelInferior.setBackground(new java.awt.Color(255, 255, 255));
        panelInferior.setLayout(new java.awt.BorderLayout());

        lblFraseOculta.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lblFraseOculta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFraseOculta.setText("F R A S E   O C U L T A");
        lblFraseOculta.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelInferior.add(lblFraseOculta, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelInferior, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        char letra = evt.getKeyChar();
        letra = Character.toUpperCase(letra);
        
        // Si el carácter recibido no es letra o la letra ya ha sido introducida
        // no se contabiliza
        if(!Character.isLetter(letra) || letrasIntroducidas.indexOf(letra) != -1)
            return;
        
        // Añadirla a la lista de letras introducidas
        letrasIntroducidas += letra;
        lblInformacion.setText(lblInformacion.getText() + " " + letra);
        
        // Se busca si la letra existe en textoOculto.
        // En caso de existir se indica este hecho y se introduce en cadenaResultado
        // y si no existe se indica que no lo hace
        boolean existeLetra = false;
        for(int i = 0; i < textoOculto.length(); ++i) {
            if(textoOculto.charAt(i) == letra) {
                existeLetra = true;
                cadenaResultado.setCharAt(i, letra);
            }
        }
        
        // Comprueba si la letra existe y actua en consecuencia
        if(existeLetra) {
            actualizarLabelFraseOculta();
            comprobarSiGana();
        } else {
            ocurrioFallo();
        }
    }//GEN-LAST:event_formKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    /**
     * Reinicia el juego para que se pueda jugar de nuevo.
     * Depende del parámetro reinicioCompleto para que la partide quede en el estado inicial
     * o solo se prepara para continuar con las frases faltantes de la lista.
     * @param reinicioCompleto Si es true el juego vuelve al estado original, si els false el juego continua con las frases que faltan.
     */
    private void reiniciarJuego(boolean reinicioCompleto) {
        if(reinicioCompleto) {
            // listaEnJuego se carga con la lista original y el índice
            // final marca el final de la lista
            listaEnJuego = titulosPelicula.clone();
            indiceFinal = listaEnJuego.length;
        }
        else {
            // Se reduce el índiceFinal que si llega a 0 es que el jugador ha ganado y se le indica.
            // El jugador podrá elegir si jugar de nuevo o cerrar el programa
            indiceFinal--;
            if(indiceFinal == 0) {
                int opcion = JOptionPane.showOptionDialog(null, "¡Enhorabuena! Ha acertado todas las películas. ¿Qué desea hacer?", "Fin de partida", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null, new String[] {"Jugar de nuevo", "Salir"}, null);
                if(opcion == 1)
                    System.exit(0);
                reiniciarJuego(true);
                return;
            }
            
            // Si todavia faltan frases se situa la frase que hay al final
            // de dicha lista a dónde estaba la última frase jugada.
            // Esto asegura de que no se van a repetir
            listaEnJuego[indiceActual] = listaEnJuego[indiceFinal];
        }
        
        // Se escoge una frase aleatoria de la lista y se pone en mayúsculas para facilitar el juego
        indiceActual = (int)(Math.random() * indiceFinal);
        textoOculto = listaEnJuego[indiceActual].toUpperCase();
        
        // Se borra la lista de letras introducidas
        letrasIntroducidas = "";
        
        // El contador de fallos se pone a 0
        fallos = 0;
        
        // Se reinician los elemntos visuales para dejarlos listos para el juego nuevo
        lblInformacion.setText("Letras: ");
        lblImagen.setIcon(imgIntentos[0]);
        reiniciarCadenaResultado();
    }
    
    /**
     * Pone carácteres de subrayado dónde debe haber letras o el signo que pertoque del textoOculto a
     * la cadenaResultado.
     */
    private void reiniciarCadenaResultado() {
        cadenaResultado = new StringBuilder(textoOculto.length());
        for(int i = 0; i < textoOculto.length(); ++i) {
            cadenaResultado.append(Character.isLetter(textoOculto.charAt(i))? '_' : textoOculto.charAt(i));
        }
        
        actualizarLabelFraseOculta();
    }
    
    /**
     * Actualiza el label, que es lo que realmente ve el usuario, al contenido de cadenaResultado.
     * Para mejorar el aspecto visual situa un espacio entre caracteres.
     */
    private void actualizarLabelFraseOculta() {
        String nuevaCadena = "";
        int i;
        for(i = 0; i < cadenaResultado.length()-1; ++i) {
            nuevaCadena += cadenaResultado.charAt(i) + " ";
        }
        nuevaCadena += cadenaResultado.charAt(i);
        
        lblFraseOculta.setText(nuevaCadena);
    }
    
    /**
     * Aumenta el contador de fallos y actualiza la imagen en consecuencia. Tambien
     * indica al usuario si ha perdido la partida y la reinicia por completo.
     */
    private void ocurrioFallo() {
        fallos++;
        if(fallos < 7)
            lblImagen.setIcon(imgIntentos[fallos]);
        if(fallos == 6) {
            JOptionPane.showMessageDialog(null, "Ha perdido", "Fin de la partida", JOptionPane.ERROR_MESSAGE);
            reiniciarJuego(true);
        }
    }
    
    /**
     * Comprueba si ha acertado todas las letras de la frase y en consecuencia informa al usuario.
     * De igual forma reinicia el juego para que pueda continuar con la siguiente frase.
     */
    private void comprobarSiGana() {
        if(cadenaResultado.indexOf("_") == -1) {
            JOptionPane.showMessageDialog(null, "Ha ganado", "Fin del juego", JOptionPane.INFORMATION_MESSAGE);
            reiniciarJuego(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFraseOculta;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JPanel panelBase;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelDibujo;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelIzquierdo;
    // End of variables declaration//GEN-END:variables
}
